[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "posture-detector"
version = "0.1.0"
description = "ERGOAI Posture Detection using OpenCV and MediaPipe"
dependencies = [
    "opencv-python",
    "mediapipe",
    "numpy",
    "pandas",
    "streamlit",
    "fastapi",
    "uvicorn",
    "python-multipart",
    "pyjwt",
    "passlib[bcrypt]",
    "sqlalchemy",
    "psycopg2-binary",
    "alembic",
    "scikit-learn",
    "websockets",
    "google-auth",
    "requests"
]

[tool.setuptools.packages.find]
where = ["src"]
