"""Add fatigue alerts count

Revision ID: 10edf0f266b3
Revises: bc6d65514b39
Create Date: 2026-08-05 18:18:26.857345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10edf0f266b3'
down_revision: Union[str, Sequence[str], None] = 'bc6d65514b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_posture_summary', sa.Column('fatigue_alerts_count', sa.Integer(), nullable=True))
    op.add_column('live_session_snapshot', sa.Column('fatigue_alerts_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_session_snapshot', 'fatigue_alerts_count')
    op.drop_column('daily_posture_summary', 'fatigue_alerts_count')
    # ### end Alembic commands ###
