"""Add dynamic deltas to calibration baseline

Revision ID: 32ebfb3a280a
Revises: 10edf0f266b3
Create Date: 2026-08-05 18:25:56.931618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ebfb3a280a'
down_revision: Union[str, Sequence[str], None] = '10edf0f266b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibration_baseline', sa.Column('neck_good_delta', sa.Float(), nullable=True))
    op.add_column('calibration_baseline', sa.Column('neck_severe_delta', sa.Float(), nullable=True))
    op.add_column('calibration_baseline', sa.Column('back_good_delta', sa.Float(), nullable=True))
    op.add_column('calibration_baseline', sa.Column('back_severe_delta', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calibration_baseline', 'back_severe_delta')
    op.drop_column('calibration_baseline', 'back_good_delta')
    op.drop_column('calibration_baseline', 'neck_severe_delta')
    op.drop_column('calibration_baseline', 'neck_good_delta')
    # ### end Alembic commands ###
