"""add avg neck and back angle to daily summary

Revision ID: bc6d65514b39
Revises: dfd2a8a7ae29
Create Date: 2026-08-05 17:50:45.359923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6d65514b39'
down_revision: Union[str, Sequence[str], None] = 'dfd2a8a7ae29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_posture_summary', sa.Column('avg_neck_angle', sa.Float(), nullable=True))
    op.add_column('daily_posture_summary', sa.Column('avg_back_angle', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_posture_summary', 'avg_back_angle')
    op.drop_column('daily_posture_summary', 'avg_neck_angle')
    # ### end Alembic commands ###
