"""Initial schema with Users

Revision ID: dfd2a8a7ae29
Revises: 
Create Date: 2026-08-05 17:16:12.739863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd2a8a7ae29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('calibration_baseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('neck_angle', sa.Float(), nullable=False),
    sa.Column('back_angle', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_baseline_id'), 'calibration_baseline', ['id'], unique=False)
    op.create_index(op.f('ix_calibration_baseline_user_id'), 'calibration_baseline', ['user_id'], unique=True)
    op.create_table('daily_posture_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('good_posture_seconds', sa.Float(), nullable=True),
    sa.Column('mild_slouch_seconds', sa.Float(), nullable=True),
    sa.Column('severe_slouch_seconds', sa.Float(), nullable=True),
    sa.Column('total_tracked_seconds', sa.Float(), nullable=True),
    sa.Column('good_posture_count', sa.Integer(), nullable=True),
    sa.Column('mild_slouch_count', sa.Integer(), nullable=True),
    sa.Column('severe_slouch_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_posture_summary_date'), 'daily_posture_summary', ['date'], unique=False)
    op.create_index(op.f('ix_daily_posture_summary_id'), 'daily_posture_summary', ['id'], unique=False)
    op.create_index(op.f('ix_daily_posture_summary_user_id'), 'daily_posture_summary', ['user_id'], unique=False)
    op.create_table('live_session_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('current_posture_label', sa.String(), nullable=False),
    sa.Column('neck_angle', sa.Float(), nullable=True),
    sa.Column('back_angle', sa.Float(), nullable=True),
    sa.Column('good_posture_percent', sa.Float(), nullable=True),
    sa.Column('bad_posture_percent', sa.Float(), nullable=True),
    sa.Column('bad_posture_seconds', sa.Float(), nullable=True),
    sa.Column('good_posture_seconds', sa.Float(), nullable=True),
    sa.Column('mild_slouch_seconds', sa.Float(), nullable=True),
    sa.Column('severe_slouch_seconds', sa.Float(), nullable=True),
    sa.Column('total_tracked_seconds', sa.Float(), nullable=True),
    sa.Column('good_posture_count', sa.Integer(), nullable=True),
    sa.Column('mild_slouch_count', sa.Integer(), nullable=True),
    sa.Column('severe_slouch_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_session_snapshot_id'), 'live_session_snapshot', ['id'], unique=False)
    op.create_index(op.f('ix_live_session_snapshot_user_id'), 'live_session_snapshot', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_session_snapshot_user_id'), table_name='live_session_snapshot')
    op.drop_index(op.f('ix_live_session_snapshot_id'), table_name='live_session_snapshot')
    op.drop_table('live_session_snapshot')
    op.drop_index(op.f('ix_daily_posture_summary_user_id'), table_name='daily_posture_summary')
    op.drop_index(op.f('ix_daily_posture_summary_id'), table_name='daily_posture_summary')
    op.drop_index(op.f('ix_daily_posture_summary_date'), table_name='daily_posture_summary')
    op.drop_table('daily_posture_summary')
    op.drop_index(op.f('ix_calibration_baseline_user_id'), table_name='calibration_baseline')
    op.drop_index(op.f('ix_calibration_baseline_id'), table_name='calibration_baseline')
    op.drop_table('calibration_baseline')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
